import Link from 'next/link';

export const metadata = { title: 'Terms of Service — Audio Transcribe' };

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100 antialiased">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="text-xs text-zinc-600 hover:text-zinc-400 transition-colors mb-10 inline-block"
        >
          ← Back
        </Link>

        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-zinc-500 text-sm mb-12">Last updated: June 2026</p>

        <div className="space-y-10 text-sm text-zinc-300 leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">What Audio Transcribe does</h2>
            <p className="text-zinc-400">
              Audio Transcribe is a web application that converts audio files to text using
              OpenAI&apos;s Whisper speech recognition model. By using this service you agree
              to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Acceptable use</h2>
            <p className="text-zinc-400 mb-3">You agree not to use this service to:</p>
            <ul className="space-y-2 list-disc list-inside text-zinc-400">
              <li>Upload audio you do not have the right to transcribe.</li>
              <li>Transcribe content that is illegal in your jurisdiction.</li>
              <li>Attempt to reverse-engineer, scrape, or overload the service.</li>
              <li>Resell or repackage the transcription output as an API product.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">OpenAI usage policies</h2>
            <p className="text-zinc-400">
              Audio processing is performed by OpenAI&apos;s Whisper API. Your use of this
              service is also subject to{' '}
              <a
                href="https://openai.com/policies/usage-policies"
                target="_blank"
                rel="noopener noreferrer"
                className="text-violet-400 hover:text-violet-300 underline underline-offset-2"
              >
                OpenAI&apos;s usage policies
              </a>
              . Do not upload audio that would violate those policies.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Accuracy</h2>
            <p className="text-zinc-400">
              Transcriptions are generated by an AI model and may contain errors — especially
              for proper nouns, technical terms, strong accents, or low-quality audio. Do not
              rely on transcripts for legal, medical, or safety-critical purposes without
              human review.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Accounts</h2>
            <p className="text-zinc-400">
              You may use the transcription feature without an account. Signing in with Google
              or GitHub allows you to save and access your transcription history. You are
              responsible for maintaining the security of your account. You may delete your
              account at any time from{' '}
              <Link href="/account" className="text-violet-400 hover:text-violet-300 underline underline-offset-2">
                Account Settings
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Service availability</h2>
            <p className="text-zinc-400">
              We make no guarantees about uptime or availability. The service depends on
              OpenAI&apos;s API, which may be unavailable or rate-limited at times. We reserve
              the right to suspend or discontinue the service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Limitation of liability</h2>
            <p className="text-zinc-400">
              This service is provided &quot;as is&quot; without warranties of any kind. We are
              not liable for any damages arising from your use of the service, including lost
              data, inaccurate transcripts, or service interruptions. Our total liability to
              you for any claim is limited to the amount you paid us in the past 12 months,
              if anything.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Changes to these terms</h2>
            <p className="text-zinc-400">
              We may update these terms from time to time. Continued use of the service after
              changes constitutes acceptance. The &quot;last updated&quot; date at the top of
              this page reflects the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-zinc-100 mb-3">Contact</h2>
            <p className="text-zinc-400">
              Questions?{' '}
              <a
                href="mailto:swathikch@gmail.com"
                className="text-violet-400 hover:text-violet-300 underline underline-offset-2"
              >
                swathikch@gmail.com
              </a>
            </p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-zinc-900 flex gap-6 text-xs text-zinc-700">
          <Link href="/privacy" className="hover:text-zinc-500 transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-zinc-500 transition-colors">Home</Link>
        </div>
      </div>
    </main>
  );
}
